CREATE TYPE affiliation_kind AS ENUM ('student','faculty_staff','alumni','visitor_other');
CREATE TYPE account_status AS ENUM ('active','suspended','deleted');
CREATE TYPE product_status AS ENUM ('draft','active','archived');
CREATE TYPE review_status AS ENUM ('pending','approved','rejected','flagged');
CREATE TYPE inventory_movement_kind AS ENUM ('receipt','reservation','release','sale','return','correction');

CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE categories(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT UNIQUE NOT NULL,slug TEXT UNIQUE NOT NULL,description TEXT NOT NULL DEFAULT '',active BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE product_types(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT UNIQUE NOT NULL,slug TEXT UNIQUE NOT NULL,attributes JSONB NOT NULL DEFAULT '[]',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE products(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),category_id UUID REFERENCES categories,product_type_id UUID REFERENCES product_types,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,short_description TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',base_price BIGINT NOT NULL CHECK(base_price>=0),compare_price BIGINT NOT NULL DEFAULT 0 CHECK(compare_price>=0),badge TEXT NOT NULL DEFAULT '',card_color TEXT NOT NULL DEFAULT '#163ea8',status product_status NOT NULL DEFAULT 'draft',featured BOOLEAN NOT NULL DEFAULT FALSE,customizable BOOLEAN NOT NULL DEFAULT FALSE,sort_order INTEGER NOT NULL DEFAULT 0,rating_average NUMERIC(3,2) NOT NULL DEFAULT 0,approved_review_count INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE product_media(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),product_id UUID NOT NULL REFERENCES products ON DELETE CASCADE,storage_key TEXT NOT NULL,alt_text TEXT NOT NULL DEFAULT '',width INTEGER,height INTEGER,sort_order INTEGER NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE product_variants(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),product_id UUID NOT NULL REFERENCES products ON DELETE CASCADE,sku TEXT UNIQUE NOT NULL,size TEXT NOT NULL,color TEXT NOT NULL,price_override BIGINT CHECK(price_override>=0),stock_on_hand INTEGER NOT NULL DEFAULT 0 CHECK(stock_on_hand>=0),reserved_stock INTEGER NOT NULL DEFAULT 0 CHECK(reserved_stock>=0 AND reserved_stock<=stock_on_hand),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(product_id,size,color));
CREATE TABLE product_customization_options(product_id UUID PRIMARY KEY REFERENCES products ON DELETE CASCADE,enabled BOOLEAN NOT NULL DEFAULT FALSE,field_label TEXT NOT NULL DEFAULT 'Name or nickname',min_characters INTEGER NOT NULL DEFAULT 1,max_characters INTEGER NOT NULL DEFAULT 16,allowed_pattern TEXT NOT NULL DEFAULT '^[A-Za-z0-9 ._-]+$',placements JSONB NOT NULL DEFAULT '["Front"]',styles JSONB NOT NULL DEFAULT '["Campus Block"]',text_colors JSONB NOT NULL DEFAULT '["White"]',surcharge BIGINT NOT NULL DEFAULT 0,added_fulfilment_days INTEGER NOT NULL DEFAULT 2,return_policy TEXT NOT NULL DEFAULT 'Customized items cannot be returned unless defective.',updated_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE hostels(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT UNIQUE NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),phone_e164 TEXT UNIQUE NOT NULL,phone_verified_at TIMESTAMPTZ,full_name TEXT NOT NULL DEFAULT '',email TEXT,affiliation affiliation_kind,is_hostel_resident BOOLEAN NOT NULL DEFAULT FALSE,hostel_id UUID REFERENCES hostels,room_number TEXT,status account_status NOT NULL DEFAULT 'active',last_login_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK((affiliation='student' AND is_hostel_resident AND hostel_id IS NOT NULL) OR (NOT is_hostel_resident AND hostel_id IS NULL)));
CREATE TABLE addresses(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users ON DELETE CASCADE,label TEXT NOT NULL DEFAULT 'Home',recipient_name TEXT NOT NULL,phone_e164 TEXT NOT NULL,line_1 TEXT NOT NULL,line_2 TEXT,landmark TEXT,city TEXT NOT NULL,state TEXT NOT NULL,postal_code TEXT NOT NULL,country_code TEXT NOT NULL DEFAULT 'IN',is_default BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE customer_sessions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users ON DELETE CASCADE,session_hash TEXT UNIQUE NOT NULL,csrf_hash TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),revoked_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE otp_challenges(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),phone_e164 TEXT NOT NULL,purpose TEXT NOT NULL,otp_hash TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,resend_count INTEGER NOT NULL DEFAULT 0,expires_at TIMESTAMPTZ NOT NULL,consumed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE coupons(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),code TEXT UNIQUE NOT NULL,type TEXT NOT NULL CHECK(type IN('percentage','fixed','free_shipping')),value BIGINT NOT NULL DEFAULT 0,min_order BIGINT NOT NULL DEFAULT 0,starts_at TIMESTAMPTZ,ends_at TIMESTAMPTZ,usage_limit INTEGER NOT NULL DEFAULT 0,per_customer_limit INTEGER NOT NULL DEFAULT 1,used_count INTEGER NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE orders(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_no TEXT UNIQUE NOT NULL,user_id UUID REFERENCES users,customer_name TEXT NOT NULL,shipping_address JSONB NOT NULL DEFAULT '{}',subtotal BIGINT NOT NULL,customization_total BIGINT NOT NULL DEFAULT 0,discount BIGINT NOT NULL DEFAULT 0,shipping BIGINT NOT NULL DEFAULT 0,tax BIGINT NOT NULL DEFAULT 0,total BIGINT NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',order_status TEXT NOT NULL DEFAULT 'placed',payment_status TEXT NOT NULL DEFAULT 'pending',fulfilment_status TEXT NOT NULL DEFAULT 'unfulfilled',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE order_items(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_id UUID NOT NULL REFERENCES orders ON DELETE CASCADE,product_id UUID REFERENCES products,variant_id UUID REFERENCES product_variants,product_name TEXT NOT NULL,slug TEXT NOT NULL,sku TEXT NOT NULL,size TEXT NOT NULL,color TEXT NOT NULL,image TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),unit_price BIGINT NOT NULL,line_total BIGINT NOT NULL,delivered_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE order_item_customizations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_item_id UUID UNIQUE NOT NULL REFERENCES order_items ON DELETE CASCADE,custom_text TEXT NOT NULL,placement TEXT NOT NULL,style TEXT NOT NULL,text_color TEXT NOT NULL,surcharge BIGINT NOT NULL DEFAULT 0,rule_snapshot JSONB NOT NULL,production_status TEXT NOT NULL DEFAULT 'pending',moderation_status TEXT NOT NULL DEFAULT 'approved',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE coupon_redemptions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),coupon_id UUID NOT NULL REFERENCES coupons,user_id UUID REFERENCES users,order_id UUID UNIQUE NOT NULL REFERENCES orders,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE inventory_movements(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),variant_id UUID NOT NULL REFERENCES product_variants,movement_type inventory_movement_kind NOT NULL,quantity_delta INTEGER NOT NULL,order_id UUID REFERENCES orders,idempotency_key TEXT UNIQUE NOT NULL,reason TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE TABLE reviews(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users,product_id UUID NOT NULL REFERENCES products,order_item_id UUID UNIQUE NOT NULL REFERENCES order_items,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),title TEXT NOT NULL DEFAULT '',body TEXT NOT NULL DEFAULT '',status review_status NOT NULL DEFAULT 'pending',moderation_reason TEXT,moderated_by UUID,submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE review_media(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),review_id UUID NOT NULL REFERENCES reviews ON DELETE CASCADE,storage_key TEXT NOT NULL,mime_type TEXT NOT NULL,width INTEGER,height INTEGER,sort_order INTEGER NOT NULL CHECK(sort_order BETWEEN 1 AND 3),processing_state TEXT NOT NULL DEFAULT 'processing',moderation_state TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(review_id,sort_order));
CREATE TABLE payment_attempts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_id UUID NOT NULL REFERENCES orders,provider TEXT NOT NULL,provider_order_id TEXT,provider_payment_id TEXT,amount BIGINT NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',status TEXT NOT NULL,idempotency_key TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE payment_webhook_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),provider TEXT NOT NULL,provider_event_id TEXT NOT NULL,event_type TEXT NOT NULL,signature_valid BOOLEAN NOT NULL,payload JSONB NOT NULL DEFAULT '{}',processing_state TEXT NOT NULL DEFAULT 'received',attempt_count INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),processed_at TIMESTAMPTZ,UNIQUE(provider,provider_event_id));
CREATE TABLE audit_log(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),actor_type TEXT NOT NULL,actor_id TEXT,action TEXT NOT NULL,detail JSONB NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE INDEX products_catalog_category_idx ON products(category_id,sort_order) WHERE status='active';
CREATE INDEX products_catalog_type_idx ON products(product_type_id,sort_order) WHERE status='active';
CREATE INDEX products_price_idx ON products(base_price) WHERE status='active';
CREATE INDEX variants_filter_idx ON product_variants(size,active,product_id);
CREATE INDEX orders_user_created_idx ON orders(user_id,created_at DESC);
CREATE INDEX orders_status_created_idx ON orders(fulfilment_status,payment_status,created_at DESC);
CREATE INDEX reviews_product_public_idx ON reviews(product_id,submitted_at DESC) WHERE status='approved';
CREATE INDEX sessions_active_idx ON customer_sessions(session_hash,expires_at) WHERE revoked_at IS NULL;
CREATE INDEX inventory_variant_created_idx ON inventory_movements(variant_id,created_at DESC);
