import assert from 'node:assert/strict';
import fs from 'node:fs';

const server=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const client=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const styles=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../migrations/004_order_operations_colorways.sql',import.meta.url),'utf8');
const mediaMigration=fs.readFileSync(new URL('../migrations/010_product_catalog_management.sql',import.meta.url),'utf8');

for(const route of ['/api/admin/orders','/api/admin/orders/summary','/api/admin/orders/matrix','/api/admin/vendor-batches','/api/admin/products/:id/customization','/api/admin/products/:id/colorways','/api/admin/products/:id/media/upload','/api/admin/media/:id','/api/admin/products/:id/restore'])assert.ok(server.includes(route),`Missing ${route}`);
for(const table of ['product_colorways','vendor_batches','vendor_batch_items','order_status_history'])assert.ok(migration.includes(`CREATE TABLE ${table}`),`Missing ${table}`);
for(const column of ['media_type','mime_type','file_size','deleted_at'])assert.ok(mediaMigration.includes(column),`Missing ${column}`);
for(const component of ['StudioOrdersV2','StudioProductsV2','StudioCatalogManager','colorway-selector','PRODUCT COLOURS','showColorwayForm','vendor-batches/preview'])assert.ok(client.includes(component),`Missing ${component}`);
for(const selector of ['.orders-workspace','.orders-filterbar','.matrix-card','.colorway-layout','.media-manager','.product-create','@media(max-width:760px)'])assert.ok(styles.includes(selector),`Missing ${selector}`);
assert.ok(client.includes('product.catalogItemId||product.id'),'Catalogue cards need stable colorway keys');
assert.ok(server.includes("vbi.id IS NULL AND o.payment_status IN('paid','captured')"),'New-vendor eligibility must require payment');
assert.ok(server.includes("'/home/data/product-media'"),'Azure App Service media must use persistent storage');
assert.ok(server.includes("pco.product_id=p.id AND pco.enabled"),'Customizable filter must require enabled rules');
assert.ok(server.includes("order_items SET delivered_at=COALESCE(delivered_at,now())"),'Delivered orders must unlock review eligibility');
assert.ok(server.includes('colorway_id IS NOT DISTINCT FROM v.colorway_id'),'Quote images must follow the selected colorway');
assert.ok(client.includes('add({...product,image:activeImage}'),'Cart must retain the selected colorway image');
assert.ok(client.includes("||result.product.colorways?.find(x=>String(x.name).toLowerCase()==='beige')"),'Product detail must default to Beige');
assert.ok(client.includes('catalog-color-dots'),'Catalogue cards must show available colour dots');
assert.ok(client.includes('aria-pressed={activeColorway?.id===colorway.id}'),'Catalogue colour dots must expose active state');
assert.ok(client.includes('onClick={event=>selectColor(event,colorway)}'),'Catalogue colour dots must switch the card thumbnail');
assert.ok(client.includes('MORE SOON'),'Storefront must include the More Soon message');
assert.ok(client.includes('function MoreSoonSection'),'More Soon message must be a standalone section');
assert.ok(client.includes('<MoreSoonSection/>'),'More Soon section must sit after the catalogue');
assert.ok(styles.includes('.more-soon'),'More Soon section must have dedicated styling');
assert.ok(!client.includes('ComingSoonCard'),'Placeholder product card must be removed');
assert.ok(!styles.includes('.coming-soon-card'),'Placeholder product-card styling must be removed');
assert.ok(styles.includes('.coupon-entry label{display:grid;gap:10px'),'Coupon label and input need intentional spacing');
assert.ok(styles.includes('.cart-address-panel h2{font-size:34px'),'Delivery address heading must be larger');
assert.ok(styles.includes('.catalog-art{height:440px'),'Product card media must be larger');
assert.ok(styles.includes('.catalog-card{background:var(--surface-raised);border-radius:20px'),'Product cards must have larger rounded backgrounds');
assert.ok(client.includes('Array.from({length:4}'),'Announcement marquees must repeat infinitely');
assert.ok(!client.includes('Customizable only'),'Storefront customizability filter must be removed');
assert.ok(!client.includes('<a href="/studio">STUDIO</a>'),'Public footer must not link to Studio');
assert.ok(client.includes('ADD TO BAG · ${money'),'Mobile Add to Bag must include the dynamic price');
assert.ok(client.includes('product.customization?.enabled?product.customization:null'),'Disabled customization must be hidden from customers');
assert.ok(client.includes('item.qty<=1?remove(item.key):update(item.key,item.qty-1)'),'Cart minus at quantity one must remove the item');
assert.ok(client.includes("localStorage.removeItem('iitd-drop-cart-v2')"),'Confirmed orders must clear persisted cart storage synchronously');
assert.ok(client.includes("const finishOrder=result=>{clear();setBusy(false);location.href='/account'}"),'Confirmed orders must redirect to the customer orders page');
assert.ok(client.includes('return {cart,add,update,remove,clear,count:'),'Cart hook must expose its clear operation');
assert.ok(client.includes('account-menu-wrap'),'Signed-in header must expose an account menu wrapper');
assert.ok(client.includes('MY ORDERS')&&client.includes('PROFILE')&&client.includes('ADDRESSES'),'Account menu must include orders, profile, and addresses links');
assert.ok(client.includes("new URLSearchParams(location.search).get('tab')"),'Account page must support menu tab links');
assert.ok(styles.includes('.account-menu-wrap:hover .account-menu,.account-menu-wrap:focus-within .account-menu'),'Account menu must open on hover and keyboard focus');
assert.ok(styles.includes('.account-profile-editor>.kicker{font-size:13px'),'Profile Details label must be larger');
assert.ok(styles.includes('.account-profile-editor p{font-size:16px'),'Profile details copy must be larger');
console.log('source self-test passed');
