import assert from 'node:assert/strict';
import fs from 'node:fs';

const blockedTerm=['off','icial'].join('');
const server=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const client=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const styles=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const seed=fs.readFileSync(new URL('../migrations/002_seed_catalogue.sql',import.meta.url),'utf8');
const preview=fs.readFileSync(new URL('../work/preview_server.py',import.meta.url),'utf8');
const workflow=fs.readFileSync(new URL('../.github/workflows/ci.yml',import.meta.url),'utf8');
const packageJson=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
const migration=fs.readFileSync(new URL('../migrations/004_order_operations_colorways.sql',import.meta.url),'utf8');
const mediaMigration=fs.readFileSync(new URL('../migrations/010_product_catalog_management.sql',import.meta.url),'utf8');
const jerseyRemoval=fs.readFileSync(new URL('../migrations/019_remove_iit_delhi_01_jersey.sql',import.meta.url),'utf8');
const priceMigration=fs.readFileSync(new URL('../migrations/018_update_drop_prices.sql',import.meta.url),'utf8');

for(const route of ['/api/admin/orders','/api/admin/orders/summary','/api/admin/orders/matrix','/api/admin/vendor-batches','/api/admin/products/:id/customization','/api/admin/products/:id/colorways','/api/admin/products/:id/media/upload','/api/admin/media/:id','/api/admin/products/:id/restore'])assert.ok(server.includes(route),`Missing ${route}`);
for(const table of ['product_colorways','vendor_batches','vendor_batch_items','order_status_history'])assert.ok(migration.includes(`CREATE TABLE ${table}`),`Missing ${table}`);
for(const column of ['media_type','mime_type','file_size','deleted_at'])assert.ok(mediaMigration.includes(column),`Missing ${column}`);
for(const component of ['StudioProductsV2','StudioCatalogManager','colorway-selector','PRODUCT COLOURS','showColorwayForm'])assert.ok(client.includes(component),`Missing ${component}`);
for(const selector of ['.orders-workspace','.orders-filterbar','.matrix-card','.colorway-layout','.media-manager','.product-create','@media(max-width:760px)'])assert.ok(styles.includes(selector),`Missing ${selector}`);
assert.ok(client.includes('product.catalogItemId||product.id'),'Catalogue cards need stable colorway keys');
assert.ok(server.includes('JOIN product_colorways cw ON cw.product_id=p.id AND cw.active AND cw.show_in_catalog'),'Public catalogue must expose one row per visible colourway');
assert.ok(client.includes('colorway.id===product.colorwayId')&&client.includes('activeColorway?.name||colors'),'Catalogue cards must initialize and label their selected colourway');
assert.ok(jerseyRemoval.includes("DELETE FROM products WHERE slug='iit-delhi-01-jersey'"),'Jersey must be deleted from the catalogue');
assert.ok(jerseyRemoval.includes('UPDATE order_items')&&jerseyRemoval.includes('product_id=NULL'),'Jersey removal must detach order history rather than rewrite it');
assert.ok(!fs.existsSync(new URL('../data/product-media/iitd-jersey-front.jpg',import.meta.url))&&!fs.existsSync(new URL('../data/product-media/iitd-jersey-back.jpg',import.meta.url)),'Jersey media must no longer ship with the deployment');
assert.ok(server.includes("vbi.id IS NULL AND o.payment_status IN('paid','captured')"),'New-vendor eligibility must require payment');
assert.ok(server.includes("'/home/data/product-media'"),'Azure App Service media must use persistent storage');
assert.ok(server.includes("const packagedMediaRoot=path.join(root,'data','product-media')")&&server.includes('hasMediaFiles'),'Production media must fall back to packaged assets when persistent storage is empty');
assert.ok(server.includes("pco.product_id=p.id AND pco.enabled"),'Customizable filter must require enabled rules');
assert.ok(server.includes("order_items SET delivered_at=COALESCE(delivered_at,now())"),'Delivered orders must unlock review eligibility');
assert.ok(server.includes('colorway_id IS NOT DISTINCT FROM v.colorway_id'),'Quote images must follow the selected colorway');
assert.ok(client.includes('add({...product,image:activeImage}'),'Cart must retain the selected colorway image');
assert.ok(client.includes("||result.product.colorways?.find(x=>String(x.name).toLowerCase()==='black')"),'Product detail must default to Black');
assert.ok(client.includes('catalog-color-dots'),'Catalogue cards must show available colour dots');
assert.ok(client.includes('catalog-card-photos')&&client.includes("slice(0,2)"),'Catalogue cards must show up to two product photos');
assert.ok(client.includes('HOSTEL')&&client.includes('ROOM NUMBER'),'Delivery settings must use hostel and room number fields');
assert.ok(!client.includes('googleMapsBrowserKey')&&!client.includes('Google Maps')&&!client.includes('mapsPlaceId'),'Client must not expose or load Google Maps credentials');
assert.ok(client.includes('aria-pressed={activeColorway?.id===colorway.id}'),'Catalogue colour dots must expose active state');
assert.ok(priceMigration.includes("slug='dogra-drip'")&&priceMigration.includes('base_price=69900')&&priceMigration.includes('compare_price=79900'),'Dogra price migration must set ₹699 with ₹799 compare price');
assert.ok(client.includes('catalog-add')&&client.includes("'pick=size'"),'Catalogue add-to-bag must route to the product page size step');
assert.ok(!client.includes('addToCart'),'Catalogue cards must not add to the bag before a size is chosen');
assert.ok(client.includes('id="select-size"')&&client.includes("document.getElementById('select-size')?.scrollIntoView"),'Size-first redirect must scroll to the size block');
assert.ok(client.includes('setTimeout(()=>setSizePrompt(false),5000)'),'Size prompt must clear itself after five seconds');
assert.ok(client.includes('setSize(x);setSizePrompt(false)'),'Size prompt must let shoppers pick a size directly');
assert.ok(styles.includes('.size-prompt{position:fixed')&&styles.includes('.size-prompt-sizes'),'Size prompt must ship themed styling');
assert.ok(!client.includes('theme-switch')&&!styles.includes('theme-switch'),'Storefront dark-mode switch must be gone');
assert.ok(client.includes("const currentMode=()=>'light'")&&!client.includes('iitd-drop-theme'),'Storefront must render light and ignore any stored dark preference');
assert.ok(client.includes('themeVars(draft,previewMode)'),'Studio must keep its own light/dark appearance preview');
const heroMigration=fs.readFileSync(new URL('../migrations/020_refresh_hero_image.sql',import.meta.url),'utf8');
assert.ok(heroMigration.includes("value='/assets/merch-hero.png?v=20260919'")&&heroMigration.includes("AND value='/assets/merch-hero.png'"),'Replaced hero art must be cache-busted without overwriting a Studio-chosen image');
assert.ok(preview.includes("'heroImage':'/assets/merch-hero.png?v=20260919'"),'Local preview must serve the same versioned hero URL');
const jerseyGone=fs.readFileSync(new URL('../migrations/021_webp_catalogue_media.sql',import.meta.url),'utf8');
assert.ok(jerseyGone.includes("replace(storage_key,'.png','.webp')"),'Catalogue media keys must move to the WebP files that ship');
assert.ok(fs.readdirSync(new URL('../data/product-media/',import.meta.url)).every(name=>name.endsWith('.webp')),'Only WebP catalogue media may ship');
assert.ok(server.includes("app.get('/api/admin/orders/fulfilment'")&&server.includes("app.patch('/api/admin/orders/:id/delivered'"),'Orders desk needs its listing and delivered toggle');
assert.ok(server.indexOf("app.get('/api/admin/orders/fulfilment'")<server.indexOf("app.get('/api/admin/orders/:id'"),'The fulfilment route must be declared before the :id route that would shadow it');
assert.ok(server.includes("'UPDATE order_items SET delivered_at=NULL WHERE order_id=$1'"),'Unticking an order must clear its delivered stamp');
assert.ok(server.includes("if(!item.product_id)return res.status(409)"),'Reviewing a retired product must fail cleanly rather than break the NOT NULL column');
assert.ok(!client.includes('review-upload')&&!styles.includes('review-upload'),'The review photo picker must go while the server stores no images');
assert.ok(client.includes('function StudioOrders({proof})')&&!client.includes('StudioOrdersV2'),'Studio must use the rebuilt orders desk');
assert.ok(client.includes("api('/api/admin/orders/fulfilment'")&&client.includes("orders-to-deliver.csv")&&client.includes("orders-delivered.csv"),'Both order tables need their own CSV export');
assert.ok(client.includes("'\ufeff'+[head,...rows]"),'CSV export must carry a BOM so Excel reads it as UTF-8');
assert.ok(client.includes('rowSpan={order.items.length}'),'Order-level columns must span the line items they belong to');
assert.ok(client.includes("order.fulfilment_status==='delivered'?'ORDER DELIVERED'"),'A ticked order must read as delivered on the customer order page');
assert.ok(client.includes('onTouchEnd={handleTouchEnd}')&&styles.includes('.pdp-zoom-canvas'),'Swipes must still navigate the gallery and the enlarged view must keep its canvas');
assert.ok(client.includes('setShownPhoto(current=>(current+1)%photos.length)')&&styles.includes('.catalog-card-photos img.shown'),'Catalogue cards must cycle front and back rather than split the frame');
assert.ok(server.includes("app.get('/api/admin/products/:id/variants'")&&server.includes("app.patch('/api/admin/variants/:id'"),'Stock desk needs its variant read and write');
assert.ok(server.includes('INSERT INTO inventory_movements(variant_id,movement_type,quantity_delta,idempotency_key,reason)'),'Every stock change must be written to the ledger');
assert.ok(server.includes('if(stock<current.reserved_stock)'),'Stock must never drop below units already reserved for paid orders');
assert.ok(server.includes("app.post('/api/admin/products/:id/duplicate'")&&server.includes('stock_on_hand,active) VALUES($1,$2,$3,$4,$5,$6,0,$7)'),'Duplicating a product must copy its shape but not its stock');
assert.ok(client.includes('function StudioVariants(')&&client.includes('<StudioVariants productId={current.id}'),'Studio products must expose the stock desk');
assert.ok(styles.includes('.stock-table')&&styles.includes('.stock-low-banner'),'Stock desk needs its table and low-stock styling');
assert.ok(client.includes('const quickStatus=async product=>')&&client.includes('const duplicate=async product=>'),'Product list needs publish and duplicate without opening the editor');
assert.ok(client.includes('className="product-search"')&&client.includes('statusFilter'),'Product list must be searchable and filterable by status');
assert.ok(client.includes('className="product-index-pick"'),'Product rows must separate selection from their quick actions');
assert.ok(styles.includes('.catalog-art{height:min(96vw,470px)'),'Mobile product cards must use the shorter photo frame');
assert.ok(client.includes("api('/api/account/orders',{headers:{'X-CSRF-Token':session.csrf}}).then(result=>setOrders(result.orders||[])).catch("),'A failed order fetch must surface rather than be swallowed');
// the preview harness has to answer everything the client calls, or local end-to-end runs pass
// on paths that only fail against the real server
for(const route of ['/api/checkout/demo-order','/api/admin/orders/fulfilment'])assert.ok(preview.includes(route),`Preview server must implement ${route}`);
assert.ok(preview.includes("hostel_id=str(body.get('hostelId',''))"),'Preview address capture must accept the hostel-only shape the client sends');
// the loyalty wallet is gone; these names must not creep back into any layer
for(const [name,text] of [['server.mjs',server],['main.jsx',client],['styles.css',styles],['preview_server.py',preview]])assert.ok(!/wallet/i.test(text),`${name} must not mention the removed loyalty wallet`);
assert.ok(server.includes('function applyQuoteTotal(quote){quote.total=quote.subtotal+quote.customizationTotal+quote.shipping-(quote.discount||0)'),'Removing the wallet took the total recomputation with it, so a coupon needs its own');
// order_status_history.field_name is CHECK-constrained to the column names; passing 'fulfilment'
// instead of 'fulfilment_status' aborts the whole transaction, which is how the delivered tick broke.
const historyFields=[...server.matchAll(/INSERT INTO order_status_history\([^)]*\)[\s\S]{0,120}?\[[^,\[\]]+,'([a-z_]+)'/g)].map(m=>m[1]);
const badHistoryFields=historyFields.filter(name=>!['order_status','payment_status','fulfilment_status'].includes(name));
assert.ok(historyFields.length>0&&!badHistoryFields.length,`order_status_history.field_name must be a constrained column name, found: ${badHistoryFields.join(', ')}`);
assert.ok(client.includes("api('/api/catalog?limit=100')")&&client.includes('activeVariants')&&client.includes('discontinued'),'Cart must reconcile discontinued products against the active catalogue');
assert.ok(client.includes('onTouchStart={handleTouchStart}')&&client.includes('onTouchEnd={handleTouchEnd}')&&client.includes('moveGallery'),'Product gallery must support swipe navigation alongside buttons');
assert.ok(client.includes('onClick={event=>selectColor(event,colorway)}'),'Catalogue colour dots must switch the card thumbnail');
assert.ok(client.includes('MORE SOON'),'Storefront must include the More Soon message');
assert.ok(client.includes('function MoreSoonSection'),'More Soon message must be a standalone section');
assert.ok(client.includes('<MoreSoonSection/>'),'More Soon section must sit after the catalogue');
assert.ok(styles.includes('.more-soon'),'More Soon message must have dedicated styling');
assert.ok(styles.includes('.catalog-card-actions')&&styles.includes('.catalog-add'),'Quick-add cards must have dedicated responsive styling');
assert.ok(styles.includes('.pdp-gallery-stage')&&styles.includes('touch-action:pan-y'),'Product gallery must expose a touch-safe swipe surface');
assert.ok(styles.includes('.cart-discontinued-notice'),'Discontinued cart cleanup must be visible to customers');
assert.ok(!client.includes('ComingSoonCard'),'Placeholder product card must be removed');
assert.ok(!styles.includes('.coming-soon-card'),'Placeholder product-card styling must be removed');
assert.ok(styles.includes('.coupon-entry label{display:grid;gap:10px'),'Coupon label and input need intentional spacing');
assert.ok(styles.includes('.cart-address-panel h2{font-size:34px'),'Delivery address heading must be larger');
assert.ok(styles.includes('.catalog-art{height:440px'),'Product card media must be larger');
assert.ok(styles.includes('.catalog-card{background:var(--surface-raised);border-radius:20px'),'Product cards must have larger rounded backgrounds');
assert.ok(client.includes('Array.from({length:4}'),'Announcement marquees must repeat infinitely');
assert.ok(!client.includes('Customizable only'),'Storefront customizability filter must be removed');
assert.ok(!client.includes('<a href="/studio">STUDIO</a>'),'Public footer must not link to Studio');
assert.ok(client.includes('ADD TO BAG · ${money'),'Mobile Add to Bag must include the dynamic price');
assert.ok(client.includes('product.customization?.enabled?product.customization:null'),'Disabled customization must be hidden from customers');
assert.ok(client.includes('item.qty<=1?remove(item.key):update(item.key,item.qty-1)'),'Cart minus at quantity one must remove the item');
assert.ok(client.includes("localStorage.removeItem('iitd-drop-cart-v2')"),'Confirmed orders must clear persisted cart storage synchronously');
assert.ok(client.includes("const finishOrder=result=>{clear();setBusy(false);location.href='/account'}"),'Confirmed orders must redirect to the customer orders page');
assert.ok(styles.includes('.order-summary>button:disabled{opacity:.45;cursor:not-allowed}'),'A disabled checkout button must look disabled rather than silently ignoring clicks');
assert.ok(client.includes("{session&&!selectedAddressId?'Choose your hostel and room number above and save it to continue.'"),'Checkout must say why it is blocked when no address is saved');
assert.ok(client.includes('return {cart,add,update,remove,clear,count:'),'Cart hook must expose its clear operation');
assert.ok(client.includes('account-menu-wrap'),'Signed-in header must expose an account menu wrapper');
assert.ok(client.includes('MY ORDERS')&&client.includes('PROFILE')&&client.includes('ADDRESSES'),'Account menu must include orders, profile, and addresses links');
assert.ok(client.includes("new URLSearchParams(location.search).get('tab')"),'Account page must support menu tab links');
assert.ok(styles.includes('.account-menu-wrap:hover .account-menu,.account-menu-wrap:focus-within .account-menu'),'Account menu must open on hover and keyboard focus');
assert.ok(client.includes('className="account-signout" onClick={signOut}>SIGN OUT<'),'Account menu must offer a sign out control');
assert.ok(client.includes("await api('/api/auth/logout',{method:'POST',headers:{'X-CSRF-Token':session.csrf}})"),'Sign out must revoke the session server-side with its CSRF token');
assert.ok(styles.includes('.account-menu a,.account-menu button{'),'Account menu must style its sign out button like its links');
assert.ok(styles.includes('.account-profile-editor>.kicker{font-size:13px'),'Profile Details label must be larger');
assert.ok(styles.includes('.account-profile-editor p{font-size:16px'),'Profile details copy must be larger');
assert.ok(styles.includes('.story>div:nth-child(2)>a{gap:20px;margin-top:30px;font-size:16px'),'Find Your Piece link must be larger');
assert.ok(styles.includes('.story>div:nth-child(2)>a svg{width:26px;height:26px'),'Find Your Piece arrow must be larger');
assert.ok(!client.includes('className="mobile-filter"'),'Public mobile filter control must be removed');
assert.ok(!client.includes('className="desktop-filters"'),'Public desktop filter controls must be removed');
assert.ok(!client.includes('className={\'filter-backdrop \''),'Public filter backdrop must be removed');
assert.ok(!client.includes('className={\'filter-sheet \''),'Public filter sheet must be removed');
assert.ok(styles.includes('.desktop-filters,.mobile-filter,.filter-backdrop,.filter-sheet{display:none!important}'),'Obsolete filter controls must stay suppressed');
assert.ok(styles.includes('@media(max-width:760px){.more-soon{display:block!important;visibility:visible;opacity:1'),'More Soon must remain visible on mobile');
assert.ok(client.includes("['darkStoryCopy','Story text'")&&client.includes("['darkKineticBackground','Ticker background'"),'Studio must expose seven independently editable dark-mode colours');
assert.ok(client.includes("'--story-copy':dark?(s.darkStoryCopy")&&client.includes("'--kinetic-background':dark?(s.darkKineticBackground"),'Dark story text and kinetic background must use separate tokens');
assert.ok(styles.includes('.kinetic-line{height:75px;background:var(--kinetic-background)'),'Kinetic carousel must use its independent background token');
assert.ok(server.includes('darkStoryCopy')&&server.includes('darkKineticBackground'),'Admin settings API must accept the independent dark-mode tokens');
assert.ok(!index.toLowerCase().includes(blockedTerm),'Public document title must not contain the blocked term');
assert.ok(!seed.toLowerCase().includes(blockedTerm),'Seeded public settings must not contain the blocked term');
assert.ok(!preview.toLowerCase().includes(blockedTerm),'Local preview settings must not contain the blocked term');
assert.ok(!fs.readFileSync(new URL('../README.md',import.meta.url),'utf8').toLowerCase().includes(blockedTerm),'Tracked project documentation must not contain the blocked term');
assert.ok(!fs.readFileSync(new URL('../scripts/setup-unix.sh',import.meta.url),'utf8').toLowerCase().includes(blockedTerm),'Tracked setup script must not contain the blocked term');
assert.ok(client.includes('useEffect(()=>{if(!initiallyOpen&&addresses.length)setOpen(false)},[addresses.length,initiallyOpen])'),'Address composer must collapse when saved addresses load');
assert.ok(client.includes('const [open,setOpen]=useState(initiallyOpen||!addresses.length)'),'Address composer must open by default only when no addresses are saved');
assert.ok(client.includes("{open&&<form className=\"address-form\""),'Address form must remain conditional on the composer state');
assert.ok(styles.includes('.back-to-store{padding:17px 19px;font-size:13px'),'Go To Merchandise control must be larger');
assert.ok(styles.includes('.order-summary>button{padding:19px 20px;font:700 13px'),'Place order control must be larger');
assert.ok(!client.includes("setEmail('admin@"),'Studio must not ship a prefilled administrator email');
assert.ok(!client.includes("setPassword('"),'Studio must not ship a prefilled administrator password');
assert.ok(client.includes('checkoutReady=Boolean(store.payment?.live||store.payment?.demoAllowed)'),'Checkout UI must expose only live or explicitly non-production demo checkout');
assert.ok(client.includes('loginReady=Boolean(store.sms?.configured||store.sms?.demoAllowed)'),'Login UI must expose only configured SMS or explicitly non-production demo SMS');
assert.ok(client.includes('CHECKOUT UNAVAILABLE'),'Production checkout must fail closed in the customer UI');
assert.ok(client.includes('SIGN-IN NOT CONFIGURED'),'Production sign-in must fail closed in the customer UI');
assert.ok(client.includes('htmlFor="studio-email"')&&client.includes('autoComplete="current-password"'),'Studio credentials must have accessible labels and autofill semantics');
assert.ok(server.includes("const demoAllowed=()=>!production")&&server.includes("provider==='demo'&&!demoAllowed()"),'Production demo OTP must be rejected');
assert.ok(server.includes("url.searchParams.set('mobile',msg91Mobile(mobile))"),'MSG91 must receive plain country-code digits, not a percent-encoded +');
assert.ok(server.includes('api.msg91.com/api/v5/widget/${path}')&&server.includes("msg91Widget('sendOtp'")&&server.includes("msg91Widget('verifyOtp'"),'Widget send and verify must both run server-side');
assert.ok(server.includes('async function establishCustomerSession'),'Sign-in paths must share one session factory');
// the whole point of the server-side widget flow: no MSG91 credential of any kind reaches the browser
const smsPayload=server.slice(server.indexOf('const smsStatus=()=>'),server.indexOf('const smsStatus=()=>')+400);
assert.ok(!/MSG91_/.test(smsPayload),'The browser payload must carry no MSG91 credential');
assert.ok(!/otp-provider\.js|tokenAuth|initSendOTP/.test(client),'The client must not load or hold the MSG91 widget token');
assert.ok(server.includes('provider_ref')&&fs.readFileSync(new URL('../migrations/023_otp_provider_reference.sql',import.meta.url),'utf8').includes('provider_ref'),'The widget reqId must be stored against the challenge, not the browser');
assert.ok(server.includes('msg91WidgetVerify(challenge.provider_ref'),'Verification must quote the stored reqId, so the number is the one we sent to');
// Razorpay will not activate an account whose site lacks these pages, so they are contract, not decoration.
for(const page of ['terms','privacy','shipping','contact'])assert.ok(client.includes(`${page}:{kicker:`),`Missing the ${page} policy page`);
for(const route of ['/terms','/privacy','/shipping','/contact'])assert.ok(server.includes(`'${route}'`),`SPA must serve ${route}`);
assert.ok(!client.includes("refund:{kicker:")&&!server.includes("'/refund'"),'The cancellations page must be gone');
assert.ok(client.includes('const POLICY_KEYS=')&&server.includes("'policyTerms','policyPrivacy','policyShipping'"),'Policy copy must be editable from Studio');
assert.ok(client.includes('function StudioPolicies(')&&client.includes("'Policies',"),'Studio needs a Policies tab');
assert.ok(client.includes('policySections(store.settings,policy,page)'),'Published pages must render the stored copy, falling back to the built-in');
assert.ok(server.includes('shipping=0,quote={currency'),'Delivery is free, so no shipping is charged');
assert.ok(client.includes("Shipping</span><b>{quote?money(quote.shipping||0)"),'The bag must show the shipping line as a zero amount');
assert.ok(!client.includes('Our story')&&!client.includes('story shell'),'The Our Story section must be gone');
assert.ok(server.includes('LEFT JOIN coupon_redemptions cr ON cr.order_id=o.id')&&server.includes('GROUP BY o.id,u.full_name,u.phone_e164,c.code'),'Coupon code must join into the orders desk and be grouped');
assert.ok(client.includes('<th>Coupon</th>')&&client.includes('orders-coupon'),'The orders desk must show which coupon was used');
assert.ok(client.includes("'Customer','Coupon','Discount','Paid value'"),'CSV export must carry the coupon and its discount');
assert.ok(client.includes("SUPPORT_EMAIL='TheIITDelhiDrop@gmail.com'"),'Support address must be the published one');
assert.ok(client.includes('className="footer-policies"')&&client.includes('href="/terms"')&&client.includes('href="/privacy"'),'Policy pages must be reachable from the footer');
assert.ok(!client.includes('· PRIVACY · TERMS · RETURNS'),'The footer must link its policies rather than name them as plain text');
assert.ok(client.includes('not an official store of'),'Policies must state the store is not an official IIT Delhi store');
assert.ok(server.includes("route:'razorpay/order'")&&server.includes("res.status(502)"),'A Razorpay order failure must answer 502 with the reason, not a blind 500');
assert.ok(client.includes('const SIZE_CHART=')&&client.includes("['XXL',50,29.5,24,10.5]"),'Size chart must carry the published measurements');
assert.ok(client.includes('onClick={()=>setSizeGuide(true)}')&&styles.includes('.size-guide-backdrop'),'The size guide link must open a chart');
assert.ok(client.includes("row[0]===size?'is-yours'")&&styles.includes('.size-guide tr.is-yours td'),'The chart must highlight the size the shopper has selected');
assert.ok(client.includes('onClick={event=>event.stopPropagation()}'),'Clicking inside the chart must not dismiss it');
assert.ok(!styles.includes("text-decoration:underline;font-size:8px"),'The size guide link must not stay at the old 8px');
assert.ok(server.includes('const adminConsoleEnabled=()=>!production')&&server.includes("if(!adminConsoleEnabled())return res.status(503)"),'Production Studio must remain disabled until explicitly enabled');
assert.ok(client.includes('Administrator access')&&client.includes('Use the administrator credentials configured for this deployment.'),'Studio must explain how to authenticate');
assert.ok(server.includes("app.post('/api/checkout/demo-order'")&&server.includes("if(!demoAllowed())return res.status(503)"),'Production demo checkout must be rejected before settlement');
assert.ok(server.includes("res.setHeader('X-Frame-Options','DENY')")&&server.includes("res.setHeader('Strict-Transport-Security'"),'Baseline browser security headers must be present');
assert.ok(server.includes("res.setHeader('Cross-Origin-Opener-Policy','same-origin-allow-popups')"),'Checkout runs its 3DS step in a popup that answers through window.opener, so COOP must allow popups');
assert.ok(server.includes("const PAID_STATUSES=['paid','captured','demo_paid'];"),'One list defines a settled payment so the order views cannot drift apart');
assert.ok(server.includes('WHERE o.user_id=$1 AND o.payment_status=ANY($2)'),'A customer must only see orders whose payment was confirmed, never a pending checkout');
assert.ok(server.includes("WHERE o.order_status<>'cancelled' AND o.payment_status=ANY($1)"),'The fulfilment desk must only list orders Razorpay has confirmed as paid');
assert.ok(!client.includes('orders-unpaid'),'The unpaid badge cannot render once unpaid orders are filtered out, so it must not linger');
assert.ok(client.includes('className="pdp-fullscreen" aria-label="View photo full screen" onClick={()=>setZoomed(true)}'),'The enlarged photo must open from an explicit full screen control');
assert.ok(!client.includes("event.target.tagName==='IMG')setZoomed(true)"),'Tapping the photo must not open the enlarged view; a stray touch would trigger it');
assert.ok(styles.includes('.pdp-gallery-stage{position:relative'),'The full screen control anchors to the photo, not to the gallery column');
assert.ok(server.includes('hostel_id,room_number')&&server.includes('SELECT id,name FROM hostels'),'Server must persist hostel delivery settings');
assert.ok(server.includes('catalogMediaJson')&&!server.includes('googleMapsBrowserKey:process.env.GOOGLE_MAPS_BROWSER_KEY'),'Server must keep the Maps key out of the public store payload and scope catalogue media');
assert.equal(packageJson.engines?.node,'22.x','Package must declare the Azure Node major');
assert.ok(workflow.includes("node-version: '22'")&&workflow.includes("npm audit --omit=dev --audit-level=high"),'CI must use Node 22 and audit production dependencies');
assert.ok(workflow.includes("find migrations -maxdepth 1 -type f -name '*.sql'")&&workflow.includes("'.env*'"),'CI must validate all migrations and exclude dotenv files from deployment');
assert.ok(workflow.includes('ADMIN_CONSOLE_ENABLED=true'),'Deployment must explicitly enable the protected Studio console');
assert.ok(preview.includes("'demoAllowed':True"),'Preview-only demo provider state must be explicit');
assert.ok(server.includes("app.post('/api/checkout/quote',rateLimit('quote'"),'The unauthenticated quote route must be rate limited; it fans out to one query per cart line');
assert.ok(server.includes('return match?match[1]:raw};')&&!server.includes('const clientIp=req=>req.ip||req.socket.remoteAddress||\'unknown\';'),'clientIp must strip the port Azure appends to the forwarded address; keyed on ip:port every rate limit resets per TCP connection and throttles nothing');
assert.ok(server.includes('if(rateBuckets.size>5000)for(const [staleKey,stale] of rateBuckets)if(now>stale.reset)rateBuckets.delete(staleKey);'),'Rate limit buckets must be pruned; the map is keyed by caller and would otherwise grow without bound');
assert.ok(workflow.includes('::add-mask::$DATABASE_URL')&&!workflow.includes('--track-status true'),'Key Vault values must be masked, and deploy status must be proved by the health check rather than the CLI tracker that reports false failures');
assert.ok(workflow.includes('group: deploy-main')&&workflow.includes('cancel-in-progress: false'),'Deployments must queue so two migration jobs never run at once');
console.log('source self-test passed');
