import assert from 'node:assert/strict';
import fs from 'node:fs';

const blockedTerm=['off','icial'].join('');
const server=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const client=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const styles=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const seed=fs.readFileSync(new URL('../migrations/002_seed_catalogue.sql',import.meta.url),'utf8');
const preview=fs.readFileSync(new URL('../work/preview_server.py',import.meta.url),'utf8');
const workflow=fs.readFileSync(new URL('../.github/workflows/ci.yml',import.meta.url),'utf8');
const packageJson=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
const migration=fs.readFileSync(new URL('../migrations/004_order_operations_colorways.sql',import.meta.url),'utf8');
const mediaMigration=fs.readFileSync(new URL('../migrations/010_product_catalog_management.sql',import.meta.url),'utf8');
const jerseyMigration=fs.readFileSync(new URL('../migrations/017_add_iit_delhi_01_jersey.sql',import.meta.url),'utf8');

for(const route of ['/api/admin/orders','/api/admin/orders/summary','/api/admin/orders/matrix','/api/admin/vendor-batches','/api/admin/products/:id/customization','/api/admin/products/:id/colorways','/api/admin/products/:id/media/upload','/api/admin/media/:id','/api/admin/products/:id/restore'])assert.ok(server.includes(route),`Missing ${route}`);
for(const table of ['product_colorways','vendor_batches','vendor_batch_items','order_status_history'])assert.ok(migration.includes(`CREATE TABLE ${table}`),`Missing ${table}`);
for(const column of ['media_type','mime_type','file_size','deleted_at'])assert.ok(mediaMigration.includes(column),`Missing ${column}`);
for(const component of ['StudioOrdersV2','StudioProductsV2','StudioCatalogManager','colorway-selector','PRODUCT COLOURS','showColorwayForm','vendor-batches/preview'])assert.ok(client.includes(component),`Missing ${component}`);
for(const selector of ['.orders-workspace','.orders-filterbar','.matrix-card','.colorway-layout','.media-manager','.product-create','@media(max-width:760px)'])assert.ok(styles.includes(selector),`Missing ${selector}`);
assert.ok(client.includes('product.catalogItemId||product.id'),'Catalogue cards need stable colorway keys');
assert.ok(server.includes('JOIN product_colorways cw ON cw.product_id=p.id AND cw.active AND cw.show_in_catalog'),'Public catalogue must expose one row per visible colourway');
assert.ok(client.includes('colorway.id===product.colorwayId')&&client.includes('activeColorway?.name||colors'),'Catalogue cards must initialize and label their selected colourway');
assert.ok(jerseyMigration.includes("'iit-delhi-01-jersey'")&&jerseyMigration.includes("'/media/iitd-jersey-front.jpg'")&&jerseyMigration.includes("'/media/iitd-jersey-back.jpg'"),'Jersey migration must add the product and two media sides');
assert.ok(fs.existsSync(new URL('../data/product-media/iitd-jersey-front.jpg',import.meta.url))&&fs.existsSync(new URL('../data/product-media/iitd-jersey-back.jpg',import.meta.url)),'Jersey front and back assets must ship with the deployment');
assert.ok(server.includes("vbi.id IS NULL AND o.payment_status IN('paid','captured')"),'New-vendor eligibility must require payment');
assert.ok(server.includes("'/home/data/product-media'"),'Azure App Service media must use persistent storage');
assert.ok(server.includes("const packagedMediaRoot=path.join(root,'data','product-media')")&&server.includes('hasMediaFiles'),'Production media must fall back to packaged assets when persistent storage is empty');
assert.ok(server.includes("pco.product_id=p.id AND pco.enabled"),'Customizable filter must require enabled rules');
assert.ok(server.includes("order_items SET delivered_at=COALESCE(delivered_at,now())"),'Delivered orders must unlock review eligibility');
assert.ok(server.includes('colorway_id IS NOT DISTINCT FROM v.colorway_id'),'Quote images must follow the selected colorway');
assert.ok(client.includes('add({...product,image:activeImage}'),'Cart must retain the selected colorway image');
assert.ok(client.includes("||result.product.colorways?.find(x=>String(x.name).toLowerCase()==='black')"),'Product detail must default to Black');
assert.ok(client.includes('catalog-color-dots'),'Catalogue cards must show available colour dots');
assert.ok(client.includes('catalog-card-photos')&&client.includes("slice(0,2)"),'Catalogue cards must show up to two product photos');
assert.ok(client.includes('HOSTEL')&&client.includes('ROOM NUMBER'),'Delivery settings must use hostel and room number fields');
assert.ok(!client.includes('googleMapsBrowserKey')&&!client.includes('Google Maps')&&!client.includes('mapsPlaceId'),'Client must not expose or load Google Maps credentials');
assert.ok(client.includes('aria-pressed={activeColorway?.id===colorway.id}'),'Catalogue colour dots must expose active state');
assert.ok(client.includes('onClick={event=>selectColor(event,colorway)}'),'Catalogue colour dots must switch the card thumbnail');
assert.ok(client.includes('MORE SOON'),'Storefront must include the More Soon message');
assert.ok(client.includes('function MoreSoonSection'),'More Soon message must be a standalone section');
assert.ok(client.includes('<MoreSoonSection/>'),'More Soon section must sit after the catalogue');
assert.ok(styles.includes('.more-soon'),'More Soon section must have dedicated styling');
assert.ok(!client.includes('ComingSoonCard'),'Placeholder product card must be removed');
assert.ok(!styles.includes('.coming-soon-card'),'Placeholder product-card styling must be removed');
assert.ok(styles.includes('.coupon-entry label{display:grid;gap:10px'),'Coupon label and input need intentional spacing');
assert.ok(styles.includes('.cart-address-panel h2{font-size:34px'),'Delivery address heading must be larger');
assert.ok(styles.includes('.catalog-art{height:440px'),'Product card media must be larger');
assert.ok(styles.includes('.catalog-card{background:var(--surface-raised);border-radius:20px'),'Product cards must have larger rounded backgrounds');
assert.ok(client.includes('Array.from({length:4}'),'Announcement marquees must repeat infinitely');
assert.ok(!client.includes('Customizable only'),'Storefront customizability filter must be removed');
assert.ok(!client.includes('<a href="/studio">STUDIO</a>'),'Public footer must not link to Studio');
assert.ok(client.includes('ADD TO BAG · ${money'),'Mobile Add to Bag must include the dynamic price');
assert.ok(client.includes('product.customization?.enabled?product.customization:null'),'Disabled customization must be hidden from customers');
assert.ok(client.includes('item.qty<=1?remove(item.key):update(item.key,item.qty-1)'),'Cart minus at quantity one must remove the item');
assert.ok(client.includes("localStorage.removeItem('iitd-drop-cart-v2')"),'Confirmed orders must clear persisted cart storage synchronously');
assert.ok(client.includes("const finishOrder=result=>{clear();setBusy(false);location.href='/account'}"),'Confirmed orders must redirect to the customer orders page');
assert.ok(client.includes('return {cart,add,update,remove,clear,count:'),'Cart hook must expose its clear operation');
assert.ok(client.includes('account-menu-wrap'),'Signed-in header must expose an account menu wrapper');
assert.ok(client.includes('MY ORDERS')&&client.includes('PROFILE')&&client.includes('ADDRESSES'),'Account menu must include orders, profile, and addresses links');
assert.ok(client.includes("new URLSearchParams(location.search).get('tab')"),'Account page must support menu tab links');
assert.ok(styles.includes('.account-menu-wrap:hover .account-menu,.account-menu-wrap:focus-within .account-menu'),'Account menu must open on hover and keyboard focus');
assert.ok(styles.includes('.account-profile-editor>.kicker{font-size:13px'),'Profile Details label must be larger');
assert.ok(styles.includes('.account-profile-editor p{font-size:16px'),'Profile details copy must be larger');
assert.ok(styles.includes('.story>div:nth-child(2)>a{gap:20px;margin-top:30px;font-size:16px'),'Find Your Piece link must be larger');
assert.ok(styles.includes('.story>div:nth-child(2)>a svg{width:26px;height:26px'),'Find Your Piece arrow must be larger');
assert.ok(!client.includes('className="mobile-filter"'),'Public mobile filter control must be removed');
assert.ok(!client.includes('className="desktop-filters"'),'Public desktop filter controls must be removed');
assert.ok(!client.includes('className={\'filter-backdrop \''),'Public filter backdrop must be removed');
assert.ok(!client.includes('className={\'filter-sheet \''),'Public filter sheet must be removed');
assert.ok(styles.includes('.desktop-filters,.mobile-filter,.filter-backdrop,.filter-sheet{display:none!important}'),'Obsolete filter controls must stay suppressed');
assert.ok(styles.includes('@media(max-width:760px){.more-soon{display:block!important;visibility:visible;opacity:1'),'More Soon must remain visible on mobile');
assert.ok(client.includes("['darkStoryCopy','Story text'")&&client.includes("['darkKineticBackground','Ticker background'"),'Studio must expose seven independently editable dark-mode colours');
assert.ok(client.includes("'--story-copy':dark?(s.darkStoryCopy")&&client.includes("'--kinetic-background':dark?(s.darkKineticBackground"),'Dark story text and kinetic background must use separate tokens');
assert.ok(styles.includes('.kinetic-line{height:75px;background:var(--kinetic-background)'),'Kinetic carousel must use its independent background token');
assert.ok(server.includes('darkStoryCopy')&&server.includes('darkKineticBackground'),'Admin settings API must accept the independent dark-mode tokens');
assert.ok(!index.toLowerCase().includes(blockedTerm),'Public document title must not contain the blocked term');
assert.ok(!seed.toLowerCase().includes(blockedTerm),'Seeded public settings must not contain the blocked term');
assert.ok(!preview.toLowerCase().includes(blockedTerm),'Local preview settings must not contain the blocked term');
assert.ok(!fs.readFileSync(new URL('../README.md',import.meta.url),'utf8').toLowerCase().includes(blockedTerm),'Tracked project documentation must not contain the blocked term');
assert.ok(!fs.readFileSync(new URL('../scripts/setup-unix.sh',import.meta.url),'utf8').toLowerCase().includes(blockedTerm),'Tracked setup script must not contain the blocked term');
assert.ok(client.includes('useEffect(()=>{if(!initiallyOpen&&addresses.length)setOpen(false)},[addresses.length,initiallyOpen])'),'Address composer must collapse when saved addresses load');
assert.ok(client.includes('const [open,setOpen]=useState(initiallyOpen||!addresses.length)'),'Address composer must open by default only when no addresses are saved');
assert.ok(client.includes("{open&&<form className=\"address-form\""),'Address form must remain conditional on the composer state');
assert.ok(styles.includes('.back-to-store{padding:17px 19px;font-size:13px'),'Go To Merchandise control must be larger');
assert.ok(styles.includes('.order-summary>button{padding:19px 20px;font:700 13px'),'Place order control must be larger');
assert.ok(!client.includes("setEmail('admin@"),'Studio must not ship a prefilled administrator email');
assert.ok(!client.includes("setPassword('"),'Studio must not ship a prefilled administrator password');
assert.ok(client.includes('checkoutReady=Boolean(store.payment?.live||store.payment?.demoAllowed)'),'Checkout UI must expose only live or explicitly non-production demo checkout');
assert.ok(client.includes('loginReady=Boolean(store.sms?.configured||store.sms?.demoAllowed)'),'Login UI must expose only configured SMS or explicitly non-production demo SMS');
assert.ok(client.includes('CHECKOUT UNAVAILABLE'),'Production checkout must fail closed in the customer UI');
assert.ok(client.includes('SIGN-IN NOT CONFIGURED'),'Production sign-in must fail closed in the customer UI');
assert.ok(client.includes('htmlFor="studio-email"')&&client.includes('autoComplete="current-password"'),'Studio credentials must have accessible labels and autofill semantics');
assert.ok(server.includes("const demoAllowed=()=>!production")&&server.includes("provider==='demo'&&!demoAllowed()"),'Production demo OTP must be rejected');
assert.ok(server.includes('const adminConsoleEnabled=()=>!production')&&server.includes("if(!adminConsoleEnabled())return res.status(503)"),'Production Studio must remain disabled until explicitly enabled');
assert.ok(client.includes('Administrator access')&&client.includes('Production requires a separate administrator identity and MFA'),'Studio must communicate its identity and MFA requirement');
assert.ok(server.includes("app.post('/api/checkout/demo-order'")&&server.includes("if(!demoAllowed())return res.status(503)"),'Production demo checkout must be rejected before settlement');
assert.ok(server.includes("res.setHeader('X-Frame-Options','DENY')")&&server.includes("res.setHeader('Strict-Transport-Security'"),'Baseline browser security headers must be present');
assert.ok(server.includes('hostel_id,room_number')&&server.includes('SELECT id,name FROM hostels'),'Server must persist hostel delivery settings');
assert.ok(server.includes('catalogMediaJson')&&!server.includes('googleMapsBrowserKey:process.env.GOOGLE_MAPS_BROWSER_KEY'),'Server must keep the Maps key out of the public store payload and scope catalogue media');
assert.equal(packageJson.engines?.node,'22.x','Package must declare the Azure Node major');
assert.ok(workflow.includes("node-version: '22'")&&workflow.includes("npm audit --omit=dev --audit-level=high"),'CI must use Node 22 and audit production dependencies');
assert.ok(workflow.includes("find migrations -maxdepth 1 -type f -name '*.sql'")&&workflow.includes("'.env*'"),'CI must validate all migrations and exclude dotenv files from deployment');
assert.ok(preview.includes("'demoAllowed':True"),'Preview-only demo provider state must be explicit');
console.log('source self-test passed');
